#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul  5 14:12:25 2021

@author: ryan
"""

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.

"""
# Generate all Fibbonacci numbers under 4 million
fibs = [1,1]

while(fibs[-1] <= 4000000):
    fibs.append(fibs[-1] + fibs[-2])

# Add up all even Fibbonacci numbers
total = 0
for i in fibs:
    if(i % 2 == 0):
        total += i

print(total)